### ISSUE TITLE
FEniCs bot crashes sometimes 

### ISSUE THREAD

**Issue by funsim** [funsim/fenicsbot#5]
``` bash
Scanning for new tweets...
Traceback (most recent call last):
  File "fenicsbot.py", line 181, in <module>
    bot.start()
  File "fenicsbot.py", line 152, in start
    solve_requests, thank_yous, help_requests = self.get_mentions()
  File "fenicsbot.py", line 102, in get_mentions
    since_id=self._last_check_id)
  File "/home/simon/.local/lib/python2.7/site-packages/twitter/api.py", line 364, in GetSearch
    json = self._RequestUrl(url, 'GET', data=parameters)
  File "/home/simon/.local/lib/python2.7/site-packages/twitter/api.py", line 3605, in _RequestUrl
    raise TwitterError(str(e))
twitter.error.TwitterError: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=None)
Aborted (core dumped)
```

**Comment by presheaf** [comment]
This should be handled in commit 357ab92.
